### ISSUE TITLE
[BUG] Foto em editar perfil 

### ISSUE THREAD

**Issue by jpcirqueira** [fga-eps-mds/2019.1-MaisMonitoria-api#12]
### **Descreva o bug**
Ao entrar na tela de perfil a foto atual do usuário não esta sendo passada para a tela de editar perfil, por conta disso se o usuário não incluir uma nova foto a mudança de perfil não será realizada.  

### **Para reproduzir o bug**
Passos para reproduzir-lo:
1. Faça login.
2. Acesse a tela de perfil.
3. Clique em "Editar perfil".
4. Faça a edição sem exportar uma nova imagem.
5. Veja o erro.

### **Comportamento esperado**
Caso o usuário não inclua uma nova foto, o campo da foto deve ser preenchido com a foto atual do usuário 

###  **Screenshots**

![bug_imagem.png](https://images.zenhubusercontent.com/5c9a34a7e4ed6a0001a65ae1/dd50b7e3-08b2-406e-a72d-651ad6d4b091)

### **Desktop (complete as seguintes informações):**
- OS: ubuntu 16.04 LTS
- Browser: Chrome
- Versão: 65.0.3325.162 (Versão oficial) 64 bits

**Comment by MatheusEstanislau** [comment]
Bug foi Corrigido na issue US26 - Formatação de Perfil (https://github.com/fga-eps-mds/2019.1-maismonitoria/issues/152) adicionando a foto atual do usuário na edição do perfil, possibilitando assim a atualização de seu registro.
